//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.WCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllProduct", Namespace="http://schemas.datacontract.org/2004/07/ProductInfo_Wcf")]
    [System.SerializableAttribute()]
    public partial class AllProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OfferPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cPNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal iPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iQohField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vImagePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OfferPrice {
            get {
                return this.OfferPriceField;
            }
            set {
                if ((this.OfferPriceField.Equals(value) != true)) {
                    this.OfferPriceField = value;
                    this.RaisePropertyChanged("OfferPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cPName {
            get {
                return this.cPNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cPNameField, value) != true)) {
                    this.cPNameField = value;
                    this.RaisePropertyChanged("cPName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCatId {
            get {
                return this.iCatIdField;
            }
            set {
                if ((this.iCatIdField.Equals(value) != true)) {
                    this.iCatIdField = value;
                    this.RaisePropertyChanged("iCatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal iPrice {
            get {
                return this.iPriceField;
            }
            set {
                if ((this.iPriceField.Equals(value) != true)) {
                    this.iPriceField = value;
                    this.RaisePropertyChanged("iPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iProdId {
            get {
                return this.iProdIdField;
            }
            set {
                if ((this.iProdIdField.Equals(value) != true)) {
                    this.iProdIdField = value;
                    this.RaisePropertyChanged("iProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iQoh {
            get {
                return this.iQohField;
            }
            set {
                if ((this.iQohField.Equals(value) != true)) {
                    this.iQohField = value;
                    this.RaisePropertyChanged("iQoh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vBrand {
            get {
                return this.vBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.vBrandField, value) != true)) {
                    this.vBrandField = value;
                    this.RaisePropertyChanged("vBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDesc {
            get {
                return this.vDescField;
            }
            set {
                if ((object.ReferenceEquals(this.vDescField, value) != true)) {
                    this.vDescField = value;
                    this.RaisePropertyChanged("vDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vImagePath {
            get {
                return this.vImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.vImagePathField, value) != true)) {
                    this.vImagePathField = value;
                    this.RaisePropertyChanged("vImagePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateCart", Namespace="http://schemas.datacontract.org/2004/07/ProductInfo_Wcf")]
    [System.SerializableAttribute()]
    public partial class CreateCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cPNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal iPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iQohField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vImagePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cPName {
            get {
                return this.cPNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cPNameField, value) != true)) {
                    this.cPNameField = value;
                    this.RaisePropertyChanged("cPName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal iPrice {
            get {
                return this.iPriceField;
            }
            set {
                if ((this.iPriceField.Equals(value) != true)) {
                    this.iPriceField = value;
                    this.RaisePropertyChanged("iPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iProdId {
            get {
                return this.iProdIdField;
            }
            set {
                if ((this.iProdIdField.Equals(value) != true)) {
                    this.iProdIdField = value;
                    this.RaisePropertyChanged("iProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iQoh {
            get {
                return this.iQohField;
            }
            set {
                if ((this.iQohField.Equals(value) != true)) {
                    this.iQohField = value;
                    this.RaisePropertyChanged("iQoh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDesc {
            get {
                return this.vDescField;
            }
            set {
                if ((object.ReferenceEquals(this.vDescField, value) != true)) {
                    this.vDescField = value;
                    this.RaisePropertyChanged("vDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vImagePath {
            get {
                return this.vImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.vImagePathField, value) != true)) {
                    this.vImagePathField = value;
                    this.RaisePropertyChanged("vImagePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductsData", ReplyAction="http://tempuri.org/IProduct/GetProductsDataResponse")]
        WebDemo.WCFService.AllProduct[] GetProductsData(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductsData", ReplyAction="http://tempuri.org/IProduct/GetProductsDataResponse")]
        System.Threading.Tasks.Task<WebDemo.WCFService.AllProduct[]> GetProductsDataAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetCreateCart", ReplyAction="http://tempuri.org/IProduct/GetCreateCartResponse")]
        WebDemo.WCFService.CreateCart GetCreateCart(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetCreateCart", ReplyAction="http://tempuri.org/IProduct/GetCreateCartResponse")]
        System.Threading.Tasks.Task<WebDemo.WCFService.CreateCart> GetCreateCartAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : WebDemo.WCFService.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<WebDemo.WCFService.IProduct>, WebDemo.WCFService.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebDemo.WCFService.AllProduct[] GetProductsData(int categoryId) {
            return base.Channel.GetProductsData(categoryId);
        }
        
        public System.Threading.Tasks.Task<WebDemo.WCFService.AllProduct[]> GetProductsDataAsync(int categoryId) {
            return base.Channel.GetProductsDataAsync(categoryId);
        }
        
        public WebDemo.WCFService.CreateCart GetCreateCart(int productId) {
            return base.Channel.GetCreateCart(productId);
        }
        
        public System.Threading.Tasks.Task<WebDemo.WCFService.CreateCart> GetCreateCartAsync(int productId) {
            return base.Channel.GetCreateCartAsync(productId);
        }
    }
}
